web:
 image: wordpress
 links:
  - mysql
 environment:
  - WORDPRESS_DB_HOST=learning-wordpress_mysql_1:3306
  - WORDPRESS_DB_USER=root
  - WORDPRESS_DB_PASSWORD=password
  - WORDPRESS_DB_NAME=my-wpdb
 ports:
  - "8082:80"
mysql:
 image: mysql
 environment:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=my-wpdb